### ISSUE TITLE
As a beta tester, I want to have the actual pagebuilder code deployed on a test environment

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/odh-web-components-pagebuilder#52]
An error occurred during deployment, I wrote an email to @danielrampanelli to ask for help

**UPDATE: 2020-01-20** 
Blocked: Some things are missing...

- [x] Minimal policy on AWS/IAM (which currently is a set of allow all for various AWS services --> too open, I do not want to open that all for a not-yet-tested application)
- [x] Additional explanation on how to setup the screenshot facility (needed for the local docker development setup)
- [x] A bug prevents route53 and cloudfront configurations (wrote an email to @danielrampanelli)

**Comment by danielrampanelli** [comment]
This problem is most probably caused by deploying the application onto the same JVM (or servlet container) - the managed beans that are identified by a unique name "collide" and the deployment ends in error you encountered.

To solve this issue, you can specify the following Spring/Spring Boot configuration options in the **application.properties** file(s):

    spring.application.name = pagebuilder-main
    spring.jmx.default-domain = pagebuilder-main

and (for the other instance/version)

    spring.application.name = pagebuilder-test
    spring.jmx.default-domain = pagebuilder-test

I've tested this briefly on a Tomcat instance, so it should work and allow you to deploy the test version.

**Comment by Piiit** [comment]
@danielrampanelli Thanks, that worked.

**Comment by Piiit** [comment]
Blocked: Some things are missing...

- [ ] Minimal policy on AWS/IAM (which currently is a set of allow all for various AWS services --> too open, I do not want to open that all for a not-yet-tested application)
- [ ] Additional explanation on how to setup the screenshot facility (needed for the local docker development setup)

**Comment by Piiit** [comment]
@danielrampanelli @bertolla @sseppi I move this PR to Testing now, since the deployment is done. We should open new Issues for bugs...

**Comment by Piiit** [comment]
https://pagebuilder2.opendatahub.testingmachine.eu is the URL for testing @ NOI

https://pagebuilder.opendatahub.testingmachine.eu is the server of Daniel

`admin/admin` to login

**Comment by bertolla** [comment]
> https://pagebuilder2.opendatahub.testingmachine.eu is the URL for testing @ NOI

After logging in the first time i got `Oops you hit a 404. Go to the front page.`

After publishing a site `duplicate` the generated link is:
https://duplicate.https//pagebuildersites.opendatahub.testingmachine.eu

and even if I remove the wrong https it does not work

Seems to be working for the rest. 
Some feedback:
- usability is ok but could be improved on
- design is kinda :unamused: 
- why is the logout button so prominent? Has it high importance?

**Comment by danielrampanelli** [comment]
Thanks for the feedback, some of the reported issues have already been fixed and will be available in the next PR. UI/UX redesign is in progress as well.
